# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'animu_downloader.ui'
#
# Created: Fri Jan  3 23:21:15 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AnimuWidget(object):
    def setupMe(self, AnimuWidget):
        AnimuWidget.setObjectName("AnimuWidget")
        AnimuWidget.resize(606, 264)
        AnimuWidget.setMinimumSize(QtCore.QSize(500, 200))
        AnimuWidget.setMaximumSize(QtCore.QSize(1000, 1000))
        AnimuWidget.setWindowTitle("Animu Downloader 1.0 alpha 4")
        AnimuWidget.setDocumentMode(True)
        AnimuWidget.setTabsClosable(False)
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setText("Aktualnie pobierana seria:")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineLinkToSeries = QtGui.QLineEdit(self.tab)
        self.lineLinkToSeries.setFrame(False)
        self.lineLinkToSeries.setObjectName("lineLinkToSeries")
        self.gridLayout_3.addWidget(self.lineLinkToSeries, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        self.label.setText("Link do serii anime:")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.lblWhatAreWeDownloading = QtGui.QLabel(self.tab)
        self.lblWhatAreWeDownloading.setText("-")
        self.lblWhatAreWeDownloading.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblWhatAreWeDownloading.setObjectName("lblWhatAreWeDownloading")
        self.gridLayout_3.addWidget(self.lblWhatAreWeDownloading, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setText("Liczba dostępnych odcinków:")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.lblEpisodesCount = QtGui.QLabel(self.tab)
        self.lblEpisodesCount.setText("-")
        self.lblEpisodesCount.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblEpisodesCount.setObjectName("lblEpisodesCount")
        self.gridLayout_3.addWidget(self.lblEpisodesCount, 3, 1, 1, 1)
        self.btnDownloadEpisodesList = QtGui.QPushButton(self.tab)
        self.btnDownloadEpisodesList.setText("Pobierz listę odcinków")
        self.btnDownloadEpisodesList.setObjectName("btnDownloadEpisodesList")
        self.gridLayout_3.addWidget(self.btnDownloadEpisodesList, 4, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        AnimuWidget.addTab(self.tab, "Anime")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lstwEpisodesToDownload = QtGui.QListWidget(self.tab_5)
        self.lstwEpisodesToDownload.setEnabled(True)
        self.lstwEpisodesToDownload.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.lstwEpisodesToDownload.setObjectName("lstwEpisodesToDownload")
        self.verticalLayout.addWidget(self.lstwEpisodesToDownload)
        self.btnSelectAll = QtGui.QPushButton(self.tab_5)
        self.btnSelectAll.setEnabled(False)
        self.btnSelectAll.setText("Zaznacz wszystkie")
        self.btnSelectAll.setObjectName("btnSelectAll")
        self.verticalLayout.addWidget(self.btnSelectAll)
        self.btnDownload = QtGui.QPushButton(self.tab_5)
        self.btnDownload.setEnabled(False)
        self.btnDownload.setText("Pobierz odcinki")
        self.btnDownload.setObjectName("btnDownload")
        self.verticalLayout.addWidget(self.btnDownload)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        AnimuWidget.addTab(self.tab_5, "Wybór odcinków")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lstwToDownload = QtGui.QListWidget(self.tab_2)
        self.lstwToDownload.setObjectName("lstwToDownload")
        self.gridLayout_5.addWidget(self.lstwToDownload, 0, 0, 1, 1)
        self.lstwToConvert = QtGui.QListWidget(self.tab_2)
        self.lstwToConvert.setObjectName("lstwToConvert")
        self.gridLayout_5.addWidget(self.lstwToConvert, 0, 1, 1, 1)
        self.pbDownloaded = QtGui.QProgressBar(self.tab_2)
        self.pbDownloaded.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbDownloaded.setMaximum(100)
        self.pbDownloaded.setProperty("value", 0)
        self.pbDownloaded.setTextVisible(True)
        self.pbDownloaded.setOrientation(QtCore.Qt.Horizontal)
        self.pbDownloaded.setInvertedAppearance(False)
        self.pbDownloaded.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.pbDownloaded.setFormat("%p%")
        self.pbDownloaded.setObjectName("pbDownloaded")
        self.gridLayout_5.addWidget(self.pbDownloaded, 1, 0, 1, 1)
        self.pbConverted = QtGui.QProgressBar(self.tab_2)
        self.pbConverted.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbConverted.setProperty("value", 0)
        self.pbConverted.setObjectName("pbConverted")
        self.gridLayout_5.addWidget(self.pbConverted, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        AnimuWidget.addTab(self.tab_2, "Status")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_12 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setHorizontalSpacing(0)
        self.gridLayout_11.setVerticalSpacing(2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lblThread5 = QtGui.QLabel(self.tab_7)
        self.lblThread5.setText("Wątek 6:")
        self.lblThread5.setObjectName("lblThread5")
        self.gridLayout_11.addWidget(self.lblThread5, 5, 0, 1, 1)
        self.pbThread14 = QtGui.QProgressBar(self.tab_7)
        self.pbThread14.setEnabled(False)
        self.pbThread14.setProperty("value", 0)
        self.pbThread14.setObjectName("pbThread14")
        self.gridLayout_11.addWidget(self.pbThread14, 14, 1, 1, 1)
        self.lblThread0 = QtGui.QLabel(self.tab_7)
        self.lblThread0.setText("Wątek 1:")
        self.lblThread0.setObjectName("lblThread0")
        self.gridLayout_11.addWidget(self.lblThread0, 0, 0, 1, 1)
        self.lblThread1 = QtGui.QLabel(self.tab_7)
        self.lblThread1.setText("Wątek 2:")
        self.lblThread1.setObjectName("lblThread1")
        self.gridLayout_11.addWidget(self.lblThread1, 1, 0, 1, 1)
        self.pbThread0 = QtGui.QProgressBar(self.tab_7)
        self.pbThread0.setEnabled(False)
        self.pbThread0.setMaximum(100)
        self.pbThread0.setProperty("value", 0)
        self.pbThread0.setTextVisible(True)
        self.pbThread0.setObjectName("pbThread0")
        self.gridLayout_11.addWidget(self.pbThread0, 0, 1, 1, 1)
        self.lblThread4 = QtGui.QLabel(self.tab_7)
        self.lblThread4.setText("Wątek 5:")
        self.lblThread4.setObjectName("lblThread4")
        self.gridLayout_11.addWidget(self.lblThread4, 4, 0, 1, 1)
        self.lblThread2 = QtGui.QLabel(self.tab_7)
        self.lblThread2.setText("Wątek 3:")
        self.lblThread2.setObjectName("lblThread2")
        self.gridLayout_11.addWidget(self.lblThread2, 2, 0, 1, 1)
        self.pbThread1 = QtGui.QProgressBar(self.tab_7)
        self.pbThread1.setEnabled(False)
        self.pbThread1.setProperty("value", 0)
        self.pbThread1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pbThread1.setObjectName("pbThread1")
        self.gridLayout_11.addWidget(self.pbThread1, 1, 1, 1, 1)
        self.pbThread2 = QtGui.QProgressBar(self.tab_7)
        self.pbThread2.setEnabled(False)
        self.pbThread2.setProperty("value", 0)
        self.pbThread2.setObjectName("pbThread2")
        self.gridLayout_11.addWidget(self.pbThread2, 2, 1, 1, 1)
        self.lblThread3 = QtGui.QLabel(self.tab_7)
        self.lblThread3.setText("Wątek 4:")
        self.lblThread3.setObjectName("lblThread3")
        self.gridLayout_11.addWidget(self.lblThread3, 3, 0, 1, 1)
        self.pbThread4 = QtGui.QProgressBar(self.tab_7)
        self.pbThread4.setEnabled(False)
        self.pbThread4.setProperty("value", 0)
        self.pbThread4.setObjectName("pbThread4")
        self.gridLayout_11.addWidget(self.pbThread4, 4, 1, 1, 1)
        self.pbThread3 = QtGui.QProgressBar(self.tab_7)
        self.pbThread3.setEnabled(False)
        self.pbThread3.setProperty("value", 0)
        self.pbThread3.setObjectName("pbThread3")
        self.gridLayout_11.addWidget(self.pbThread3, 3, 1, 1, 1)
        self.lblThread6 = QtGui.QLabel(self.tab_7)
        self.lblThread6.setText("Wątek 7:")
        self.lblThread6.setObjectName("lblThread6")
        self.gridLayout_11.addWidget(self.lblThread6, 6, 0, 1, 1)
        self.pbThread5 = QtGui.QProgressBar(self.tab_7)
        self.pbThread5.setEnabled(False)
        self.pbThread5.setProperty("value", 0)
        self.pbThread5.setObjectName("pbThread5")
        self.gridLayout_11.addWidget(self.pbThread5, 5, 1, 1, 1)
        self.pbThread6 = QtGui.QProgressBar(self.tab_7)
        self.pbThread6.setEnabled(False)
        self.pbThread6.setProperty("value", 0)
        self.pbThread6.setObjectName("pbThread6")
        self.gridLayout_11.addWidget(self.pbThread6, 6, 1, 1, 1)
        self.pbThread7 = QtGui.QProgressBar(self.tab_7)
        self.pbThread7.setEnabled(False)
        self.pbThread7.setProperty("value", 0)
        self.pbThread7.setObjectName("pbThread7")
        self.gridLayout_11.addWidget(self.pbThread7, 7, 1, 1, 1)
        self.lblThread7 = QtGui.QLabel(self.tab_7)
        self.lblThread7.setText("Wątek 8:")
        self.lblThread7.setObjectName("lblThread7")
        self.gridLayout_11.addWidget(self.lblThread7, 7, 0, 1, 1)
        self.lblThread8 = QtGui.QLabel(self.tab_7)
        self.lblThread8.setText("Wątek 9:")
        self.lblThread8.setObjectName("lblThread8")
        self.gridLayout_11.addWidget(self.lblThread8, 8, 0, 1, 1)
        self.lblThread9 = QtGui.QLabel(self.tab_7)
        self.lblThread9.setText("Wątek 10:")
        self.lblThread9.setObjectName("lblThread9")
        self.gridLayout_11.addWidget(self.lblThread9, 9, 0, 1, 1)
        self.pbThread8 = QtGui.QProgressBar(self.tab_7)
        self.pbThread8.setEnabled(False)
        self.pbThread8.setProperty("value", 0)
        self.pbThread8.setObjectName("pbThread8")
        self.gridLayout_11.addWidget(self.pbThread8, 8, 1, 1, 1)
        self.lblThreadA = QtGui.QLabel(self.tab_7)
        self.lblThreadA.setText("Wątek 11:")
        self.lblThreadA.setObjectName("lblThreadA")
        self.gridLayout_11.addWidget(self.lblThreadA, 10, 0, 1, 1)
        self.pbThread9 = QtGui.QProgressBar(self.tab_7)
        self.pbThread9.setEnabled(False)
        self.pbThread9.setProperty("value", 0)
        self.pbThread9.setObjectName("pbThread9")
        self.gridLayout_11.addWidget(self.pbThread9, 9, 1, 1, 1)
        self.pbThread10 = QtGui.QProgressBar(self.tab_7)
        self.pbThread10.setEnabled(False)
        self.pbThread10.setProperty("value", 0)
        self.pbThread10.setObjectName("pbThread10")
        self.gridLayout_11.addWidget(self.pbThread10, 10, 1, 1, 1)
        self.lblThreadB = QtGui.QLabel(self.tab_7)
        self.lblThreadB.setText("Wątek 12:")
        self.lblThreadB.setObjectName("lblThreadB")
        self.gridLayout_11.addWidget(self.lblThreadB, 11, 0, 1, 1)
        self.lblThreadC = QtGui.QLabel(self.tab_7)
        self.lblThreadC.setText("Wątek 13:")
        self.lblThreadC.setObjectName("lblThreadC")
        self.gridLayout_11.addWidget(self.lblThreadC, 12, 0, 1, 1)
        self.pbThread11 = QtGui.QProgressBar(self.tab_7)
        self.pbThread11.setEnabled(False)
        self.pbThread11.setProperty("value", 0)
        self.pbThread11.setObjectName("pbThread11")
        self.gridLayout_11.addWidget(self.pbThread11, 11, 1, 1, 1)
        self.lblThreadD = QtGui.QLabel(self.tab_7)
        self.lblThreadD.setText("Wątek 14:")
        self.lblThreadD.setObjectName("lblThreadD")
        self.gridLayout_11.addWidget(self.lblThreadD, 13, 0, 1, 1)
        self.pbThread12 = QtGui.QProgressBar(self.tab_7)
        self.pbThread12.setEnabled(False)
        self.pbThread12.setProperty("value", 0)
        self.pbThread12.setObjectName("pbThread12")
        self.gridLayout_11.addWidget(self.pbThread12, 12, 1, 1, 1)
        self.lblThreadE = QtGui.QLabel(self.tab_7)
        self.lblThreadE.setText("Wątek 15:")
        self.lblThreadE.setObjectName("lblThreadE")
        self.gridLayout_11.addWidget(self.lblThreadE, 14, 0, 1, 1)
        self.pbThread13 = QtGui.QProgressBar(self.tab_7)
        self.pbThread13.setEnabled(False)
        self.pbThread13.setProperty("value", 0)
        self.pbThread13.setObjectName("pbThread13")
        self.gridLayout_11.addWidget(self.pbThread13, 13, 1, 1, 1)
        self.lblThreadF = QtGui.QLabel(self.tab_7)
        self.lblThreadF.setText("Wątek 16:")
        self.lblThreadF.setObjectName("lblThreadF")
        self.gridLayout_11.addWidget(self.lblThreadF, 15, 0, 1, 1)
        self.pbThread15 = QtGui.QProgressBar(self.tab_7)
        self.pbThread15.setEnabled(False)
        self.pbThread15.setProperty("value", 0)
        self.pbThread15.setObjectName("pbThread15")
        self.gridLayout_11.addWidget(self.pbThread15, 15, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 2)
        AnimuWidget.addTab(self.tab_7, "Pobieranie")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.txtLogs = QtGui.QPlainTextEdit(self.tab_3)
        self.txtLogs.setFrameShadow(QtGui.QFrame.Plain)
        self.txtLogs.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.txtLogs.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtLogs.setUndoRedoEnabled(False)
        self.txtLogs.setReadOnly(True)
        self.txtLogs.setPlainText("")
        self.txtLogs.setObjectName("txtLogs")
        self.gridLayout.addWidget(self.txtLogs, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        AnimuWidget.addTab(self.tab_3, "Logi")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_5 = QtGui.QLabel(self.tab_4)
        self.label_5.setText("Liczba równoległych pobrań:")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 0, 0, 1, 1)
        self.chkbConvert = QtGui.QCheckBox(self.tab_4)
        self.chkbConvert.setText("Konwertuj pobrane odcinki")
        self.chkbConvert.setObjectName("chkbConvert")
        self.gridLayout_7.addWidget(self.chkbConvert, 2, 0, 1, 1)
        self.sbDownloadThreads = QtGui.QSpinBox(self.tab_4)
        self.sbDownloadThreads.setWrapping(False)
        self.sbDownloadThreads.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sbDownloadThreads.setMinimum(1)
        self.sbDownloadThreads.setMaximum(16)
        self.sbDownloadThreads.setObjectName("sbDownloadThreads")
        self.gridLayout_7.addWidget(self.sbDownloadThreads, 0, 1, 1, 1)
        self.sbConvThreads = QtGui.QSpinBox(self.tab_4)
        self.sbConvThreads.setEnabled(False)
        self.sbConvThreads.setMinimum(1)
        self.sbConvThreads.setMaximum(8)
        self.sbConvThreads.setObjectName("sbConvThreads")
        self.gridLayout_7.addWidget(self.sbConvThreads, 4, 1, 1, 1)
        self.lineConvVideoSize = QtGui.QLineEdit(self.tab_4)
        self.lineConvVideoSize.setEnabled(False)
        self.lineConvVideoSize.setInputMask("dDDD\\xdDDD; ")
        self.lineConvVideoSize.setCursorPosition(0)
        self.lineConvVideoSize.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineConvVideoSize.setObjectName("lineConvVideoSize")
        self.gridLayout_7.addWidget(self.lineConvVideoSize, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_4)
        self.label_4.setText("Zmień rozmiar wideo:")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_4)
        self.label_6.setText("<html><head/><body><p align=\"center\">Ilość wątków używana</p><p align=\"center\">do konwertowania odcinków:</p></body></html>")
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 4, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.tab_4)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_7.addWidget(self.line_2, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_4)
        self.label_7.setText("Konwertuj do formatu:")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 5, 0, 1, 1)
        self.line = QtGui.QFrame(self.tab_4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_7.addWidget(self.line, 1, 0, 1, 1)
        self.cbOutputFormat = QtGui.QComboBox(self.tab_4)
        self.cbOutputFormat.setEnabled(False)
        self.cbOutputFormat.setProperty("currentText", "mp4")
        self.cbOutputFormat.setObjectName("cbOutputFormat")
        self.cbOutputFormat.addItem("")
        self.cbOutputFormat.setItemText(0, "mp4")
        self.cbOutputFormat.addItem("")
        self.cbOutputFormat.setItemText(1, "3gp")
        self.cbOutputFormat.addItem("")
        self.cbOutputFormat.setItemText(2, "mkv")
        self.cbOutputFormat.addItem("")
        self.cbOutputFormat.setItemText(3, "flv")
        self.gridLayout_7.addWidget(self.cbOutputFormat, 5, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab_4)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 6, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        AnimuWidget.addTab(self.tab_4, "Ustawienia")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtGui.QLabel(self.tab_6)
        self.label_8.setText("<html><head/><body><p align=\"center\">Aplikacja została napisana w języku <a href=\"http://www.python.org/\"><span style=\" text-decoration: underline; color:#0000ff;\">Python</span></a> i używa do działania biblioteki <a href=\"http://qt-project.org/\"><span style=\" text-decoration: underline; color:#0000ff;\">Qt4</span></a>(dzięki <a href=\"http://qt-project.org/wiki/PySide\"><span style=\" text-decoration: underline; color:#0000ff;\">PySide</span></a>).</p><p align=\"center\">Autor: Pampi von APi.</p><p align=\"center\">e-mail: apisoftworks@mail.ru</p><p align=\"center\">Jabber/XMPP: apisoftworks@aqq.eu</p><p align=\"center\">Najnowszą wersję programu można pobrać ze strony: <a href=\"http://apisoftworks.tk/\"><span style=\" text-decoration: underline; color:#0000ff;\">apisoftworks.tk</span></a></p></body></html>")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_8.setWordWrap(True)
        self.label_8.setOpenExternalLinks(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        AnimuWidget.addTab(self.tab_6, "O programie")

        self.retranslateUi(AnimuWidget)
        AnimuWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AnimuWidget)

    def retranslateUi(self, AnimuWidget):
        pass

